blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/stanlemon/who-can-my-daughter-date/discussions
    about: Ask questions or start discussions about the project
  - name: Security Vulnerability
    url: https://github.com/stanlemon/who-can-my-daughter-date/security/advisories/new
    about: Report security vulnerabilities privately
